In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1,2,3,4,5])


# O un array de dos dimensiones (bidimensional)
array_bidim = np.array([[1, 2, 3],
                        [4, 5, 6]])

# O un array de tres dimensiones (tridimensional)
array_tridim = np.array([[[1, 2, 3],
                          [4, 5, 6]],
                         [[7, 8, 9],
                          [10, 11, 12]]])


Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)


((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Atributos del array bidimensional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Atributos del array tridimensional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd
datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
zeros = np.zeros((2, 4, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 101, 5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[6, 8, 0, 3, 7],
       [7, 4, 2, 0, 5]])

In [ ]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3, 5))
array_3

array([[0.47330809, 0.83189427, 0.01102991, 0.48381291, 0.34259454],
       [0.05313477, 0.03038794, 0.88980017, 0.57082692, 0.70235792],
       [0.11542255, 0.36165748, 0.6135154 , 0.16029149, 0.1310827 ]])

In [ ]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, (3, 5))
array_4


array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [ ]:
# Encontramos los valores únicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [ ]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [ ]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [ ]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [ ]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))

In [ ]:
# invocamos el array_5
array_5

array([[1, 2, 0, 3],
       [3, 5, 3, 5],
       [0, 7, 7, 4]])

In [ ]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Sumamos los dos arrays
array_5 + array_6

array([[2., 3., 1., 4.],
       [4., 6., 4., 6.],
       [1., 8., 8., 5.]])

In [ ]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7

ValueError: ignored

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [ ]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Restamos el array_8 al array_7
array_7 - array_8

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [ ]:
# invocamos el array_9
array_9

array([[2, 2, 4],
       [1, 4, 1],
       [1, 1, 2]])

In [ ]:
# invocamos el array_10
array_10

array([[3, 3, 2],
       [3, 2, 1],
       [4, 4, 4]])

In [ ]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[ 6,  6,  2],
       [ 6,  4,  2],
       [12, 16, 12]])

In [ ]:
# Elevamos el array_9 al cuadrado
array_9**2

array([[ 4,  4,  1],
       [ 4,  4,  4],
       [ 9, 16,  9]])

In [ ]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[1.73205081, 1.73205081, 1.41421356],
       [1.73205081, 1.41421356, 1.        ],
       [2.        , 2.        , 2.        ]])

In [ ]:
# Hallamos el promedio de los valores del array_9
array_9.mean()

2.3333333333333335

In [ ]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [ ]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [ ]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9, 1))

In [ ]:
# invocamos el array_11
array_11

array([[2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [3],
       [4],
       [3]])

In [ ]:
# Transponemos el array_11
array_11.T

array([[2, 2, 1, 2, 2, 2, 3, 4, 3]])

In [ ]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

¿Qué tipos de datos forman parte del array de resultados?

In [ ]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [ ]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[False, False, False],
       [False,  True, False],
       [False,  True, False]])

In [ ]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [ ]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)

array([[1, 2, 2],
       [2, 2, 2],
       [3, 3, 4]])